using Unity.Burst;
using Unity.Entities;
using Unity.Physics;
using Unity.Physics.Systems;
using Components;

// Run this in the fixed step, directly after the physics engine calculates collisions and new velocities.
[UpdateInGroup(typeof(FixedStepSimulationSystemGroup))]
[UpdateAfter(typeof(PhysicsSystemGroup))]
[BurstCompile]
public partial struct PlanarMovementSystem : ISystem
{
    [BurstCompile]
    public void OnUpdate(ref SystemState state)
    {
        // Query for all entities that have a PlayerTag and a PhysicsVelocity
        foreach (var velocity in SystemAPI.Query<RefRW<PhysicsVelocity>>().WithAll<PlayerTag>())
        {
            // Nullify any vertical velocity generated by collision impulses
            velocity.ValueRW.Linear.y = 0f;
        }
    }
}